### PR TITLE
feat: mvp of scratch deploy (mostly misses checks)

### PR DESCRIPTION
**Pull request by arwer13**
NB: there are two contracts changes: they are not new: just moved from develop branch of lido-dao. These contracts do not correspond / intended to correspond to the contracts deployed on mainnet. They are used only during scratch deployment.

### CODE REVIEW

**Comment by tamtamchik** [comment]
All checks are green now! 💚

**Comment by mymphe** [comment]
Hey, thanks for this long-awaited PR!

The script seems to be running smoothly but the acceptance tests fail
image

**Comment by tamtamchik** [comment]
I have a bit different error:

```
========================================
Started script scratch-acceptance-test.ts
========================================
[×] ProviderError: Sender doesn't have enough funds to send tx. The max upfront cost is: 30000118200000000 and the sender's balance is: 0.
    at EdrProviderWrapper.request (core/node_modules/.pnpm/hardhat@2.22.2_ts-node@10.9.2_typescript@5.4.4/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:424:19)
    at async HardhatEthersSigner.sendTransaction (core/node_modules/.pnpm/@nomicfoundation+hardhat-ethers@3.0.5_ethers@6.11.1_hardhat@2.22.2/node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (core/node_modules/.pnpm/ethers@6.11.1/node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.transfer (core/node_modules/.pnpm/ethers@6.11.1/node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async checkLDOCanBeTransferred (core/scripts/scratch/scratch-acceptance-test.ts:126:3)
    at async main (core/scripts/scratch/scratch-acceptance-test.ts:65:3)
```

**Comment by arwer13** [comment]
@tamtamchik @mymphe Pushed a fix presumably. Does it work now?

**Comment by tamtamchik** [comment]
https://github.com/NomicFoundation/edr/issues/384 blocks scratch deployment on my machine.
Presumably, because of the platform, I have an Intel-based MacBook Pro. But it works on Apple Silicone-based Macs without any trouble.

> Yep, the balance problem is fixed; now it fails on `checkLdoCanBeTransferred`:
> 
> ```
> ========================================
> Started script scratch-acceptance-test.ts
> ========================================
> [×] ProviderError: Invalid parent hash: 0xf3101d3f887dd74be2145397f5f4dee53cfad212675a4277646c427b70763c83. Expected: 0xedf2e2b8ac412be8489533724a31340a7b14f3185d2ff132df1002c12f2c16cc.
>     at EdrProviderWrapper.request (core/node_modules/.pnpm/hardhat@2.22.2_ts-node@10.9.2_typescript@5.4.4/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:424:19)
>     at async HardhatEthersSigner.sendTransaction (core/node_modules/.pnpm/@nomicfoundation+hardhat-ethers@3.0.5_ethers@6.11.1_hardhat@2.22.2/node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
>     at async send (core/node_modules/.pnpm/ethers@6.11.1/node_modules/ethers/src.ts/contract/contract.ts:313:20)
>     at async Proxy.transfer (core/node_modules/.pnpm/ethers@6.11.1/node_modules/ethers/src.ts/contract/contract.ts:352:16)
>     at async checkLdoCanBeTransferred (core/scripts/scratch/scratch-acceptance-test.ts:128:3)
>     at async main (core/scripts/scratch/scratch-acceptance-test.ts:66:3)
> ```

**Pull request merged**
